spring:
  application:
    name: e2e-tests
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/it_mentor_community_platform
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

docker:
  image:
    tags:
      gateway: ${GATEWAY_DOCKER_IMAGE_TAG:}
      auth-service: ${AUTH_SERVICE_DOCKER_IMAGE_TAG:}
      data-importer: ${DATA_IMPORTER_DOCKER_IMAGE_TAG:}
      profile-service: ${PROFILE_SERVICE_DOCKER_IMAGE_TAG:}
      project-service: ${PROJECT_SERVICE_DOCKER_IMAGE_TAG:}
      mentor-service: ${MENTOR_SERVICE_DOCKER_IMAGE_TAG:}
      job-market-analytics-service: ${JOB_MARKET_ANALYTICS_SERVICE_DOCKER_IMAGE_TAG:}